### ISSUE TITLE
Type + precision, and metadata bytes order

### ISSUE THREAD

**Issue by paulsmith** [TWKB/twkb.js#1]
The [specification](https://github.com/TWKB/Specification/blob/master/twkb.md) says the first byte is type & precision, and the second byte is metadata indicating if there are ID and size bytes, but the [decoder parses the first byte as ID and size info](https://github.com/TWKB/twkb.js/blob/master/decoder.js#L235), and [the second byte as having geometry type and dimensions](https://github.com/TWKB/twkb.js/blob/master/decoder.js#L253).

Which is correct?

**Comment by nicklasaven** [comment]
Hallo

Yes, you are right. That is because the specification was just changed.

The specification is right.

PostGIS trunk follows the specification.

There is a decoder in C in PostGIS that follows the spec:
http://trac.osgeo.org/postgis/browser/trunk/liblwgeom/lwin_twkb.c

And I have written a Javascript decoder for the new spec. But my Javascript is no as it should so I have asked some one else to rewrite it :-)

But you can find it here:
http://109.74.203.88/twkb_node/twkb.js

And those demos is running the new spec:
http://109.74.203.88/twkb_node
http://109.74.203.88/twkb_test

Thanks for your interest and thanks for telling. I will put a note at the javascript decoder that it is dated.

Thank you

**Comment by bjornharrtell** [comment]
Please commit the new code. Better ugly and correct code than nice looking and wrong. :)

Also, I would love to see this easily usable with ol3  which is something I'm prepared to contribute to. I'm thinking it should be used as an optional external dependency just like rtree is today in ol3 with a thin layer to expose it as ol.format.TWKB.

**Comment by javisantana** [comment]
fixed in current implementation
